version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - apps/*
      - packages/*
    schedule:
      interval: daily
      time: "00:58"
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "deps:"
    assignees:
      - ismailgunayy

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    commit-message:
      prefix: "ci:"
    assignees:
      - ismailgunayy
