version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/api
    ignore:
      - dependency-name: "@repo/*"
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "deps(api):"
    assignees:
      - ismailgunayy

  - package-ecosystem: npm
    directory: /apps/client
    ignore:
      - dependency-name: "@repo/*"
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "deps(client):"
    assignees:
      - ismailgunayy

  - package-ecosystem: npm
    directories:
      - /shared/*
    ignore:
      - dependency-name: "@repo/*"
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "deps(shared):"
    assignees:
      - ismailgunayy

  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "deps(root):"
    assignees:
      - ismailgunayy

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    commit-message:
      prefix: "ci(github-actions):"
    assignees:
      - ismailgunayy

  - package-ecosystem: docker
    directories:
      - apps/*
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    commit-message:
      prefix: "ci(docker):"
    assignees:
      - ismailgunayy
