services:
  postgres:
    image: postgres:13.22-alpine
    container_name: shortn-prod-postgres
    env_file:
      - .env.local.prod
    environment:
      POSTGRES_DB: shortn
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shortn"]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data
    networks:
      - shortn-prod-network
    restart: unless-stopped

  redis:
    image: redis:8.2-alpine
    container_name: shortn-prod-redis
    command: redis-server --requirepass password
    env_file:
      - .env.local.prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5
    ports:
      - 6381:6379
    volumes:
      - redis-prod-data:/data
    networks:
      - shortn-prod-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: shortn-prod-api
    env_file:
      - .env.local.prod
    ports:
      - 3124:3124
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shortn-prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      args:
        VITE_MODE: ${VITE_MODE:-production}
        VITE_CLIENT_HOST: ${VITE_CLIENT_HOST:-localhost}
        VITE_CLIENT_URL: ${VITE_CLIENT_URL:-http://localhost:3024}
        VITE_API_BASE_URL: ${API_BASE_URL:-http://localhost:3124}
        VITE_API_BASE_URL_SERVER: ${API_BASE_URL:-http://api:3124}
        VITE_DOCS_URL: ${DOCS_URL:-http://localhost:3124}
        VITE_PORT: 3024
    container_name: shortn-prod-client
    env_file:
      - .env.local.prod
    ports:
      - 3024:3024
    depends_on:
      - api
    networks:
      - shortn-prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  postgres-prod-data:
  redis-prod-data:

networks:
  shortn-prod-network:
