services:
  postgres:
    image: ghcr.io/railwayapp-templates/postgres-ssl:16
    container_name: shortn-dev-postgres
    env_file:
      - .env.local.dev
    environment:
      POSTGRES_DB: shortn
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shortn"]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - shortn-dev-network

  redis:
    image: redis:8.2-alpine
    container_name: shortn-dev-redis
    command: redis-server --requirepass password
    env_file:
      - .env.local.dev
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5
    ports:
      - 6381:6379
    volumes:
      - redis-dev-data:/data
    networks:
      - shortn-dev-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    container_name: shortn-dev-api
    env_file:
      - .env.local.dev
    ports:
      - 3124:3124
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shortn-dev-network
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile.dev
      args:
        VITE_MODE: ${VITE_MODE:-development}
        VITE_CLIENT_HOST: ${VITE_CLIENT_HOST:-localhost}
        VITE_CLIENT_URL: ${VITE_CLIENT_URL:-http://localhost:3024}
        VITE_API_BASE_URL: ${API_BASE_URL:-http://localhost:3124}
        VITE_API_BASE_URL_SERVER: ${API_BASE_URL_SERVER:-http://api:3124}
        VITE_DOCS_URL: ${DOCS_URL:-http://localhost:3124}
        VITE_PORT: 3024
    container_name: shortn-dev-client
    env_file:
      - .env.local.dev
    ports:
      - 3024:3024
    volumes:
      - ./apps/client:/app/apps/client
      - /app/apps/client/node_modules
      - /app/node_modules
    depends_on:
      - api
    networks:
      - shortn-dev-network
    restart: unless-stopped

volumes:
  postgres-dev-data:
  redis-dev-data:

networks:
  shortn-dev-network:
