services:
  postgres:
    image: postgres:13.22-alpine
    container_name: shortn-prod-postgres
    env_file:
      - .env.local.prod
    environment:
      POSTGRES_DB: shortn
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shortn"]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - shortn-prod-network
    restart: unless-stopped

  redis:
    image: redis:8.2-alpine
    container_name: shortn-prod-redis
    command: ["redis-server", "--requirepass", "password"]
    env_file:
      - .env.local.dev
    ports:
      - 6379:6379
    volumes:
      - redis-dev-data:/data
    networks:
      - shortn-prod-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: shortn-prod-api
    env_file:
      - .env.local.prod
    ports:
      - 8023:8023
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shortn-prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      args:
        VITE_CLIENT_HOST: ${VITE_CLIENT_HOST:-localhost}
        VITE_CLIENT_URL: ${VITE_CLIENT_URL:-http://localhost:3023}
        VITE_API_BASE_URL: ${API_BASE_URL:-http://localhost:8023}
        VITE_API_BASE_URL_SERVER: ${API_BASE_URL:-http://localhost:8023}
        VITE_PORT: 3023
    container_name: shortn-prod-client
    env_file:
      - .env.local.prod
    ports:
      - 3023:3023
    depends_on:
      - api
    networks:
      - shortn-prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  postgres-dev-data:
  redis-dev-data:

networks:
  shortn-prod-network:
