services:
  postgres:
    image: postgres:13.22-alpine
    container_name: shortn_postgres_prod
    env_file:
      - .env.local.prod
    environment:
      POSTGRES_DB: shortn
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shortn"]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - shortn-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: shortn_api_prod
    env_file:
      - .env.local.prod
    ports:
      - 8023:8023
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shortn-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      args:
        VITE_CLIENT_HOST: ${VITE_CLIENT_HOST:-localhost}
        VITE_CLIENT_URL: ${VITE_CLIENT_URL:-http://localhost:3023}
        VITE_API_BASE_URL: ${API_BASE_URL:-http://localhost:8023}
        VITE_API_BASE_URL_SERVER: ${API_BASE_URL:-http://localhost:8023}
        VITE_PORT: 3023
    container_name: shortn_client_prod
    env_file:
      - .env.local.prod
    ports:
      - 3023:3023
    depends_on:
      - api
    networks:
      - shortn-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  postgres_data_prod:

networks:
  shortn-network:
