name: shortn

on:
  push:
    branches: [master]

jobs:
  changes:
    name: detect-changes
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
      client: ${{ steps.changes.outputs.client }}
      shared: ${{ steps.changes.outputs.shared }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api:
              - 'apps/api/**'
            client:
              - 'apps/client/**'
            shared:
              - 'packages/**'
              - 'package.json'
              - 'yarn.lock'
              - 'turbo.json'
              - '.nvmrc'

  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: ".nvmrc"
      - name: Cache node_modules
        uses: actions/cache@v4.2.3
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

  check-types:
    name: check-types
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: ".nvmrc"
      - name: Restore cache
        uses: actions/cache@v4.2.3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Check Types
        run: yarn check-types

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: ".nvmrc"
      - name: Restore cache
        uses: actions/cache@v4.2.3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Lint Code
        run: yarn lint

  build-api:
    name: build-api
    runs-on: ubuntu-latest
    needs: [setup, check-types, lint]
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: ".nvmrc"
      - name: Restore cache
        uses: actions/cache@v4.2.3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Build
        run: |
          yarn global add @railway/cli
          railway link --project=${{ vars.RAILWAY_PROJECT_ID }} --service=${{ vars.RAILWAY_API_SERVICE_ID}}
          railway run yarn build:api

  build-client:
    name: build-client
    runs-on: ubuntu-latest
    needs: [setup, check-types, lint]
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: ".nvmrc"
      - name: Restore cache
        uses: actions/cache@v4.2.3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Build
        run: |
          yarn global add @railway/cli
          railway link --project=${{ vars.RAILWAY_PROJECT_ID }} --service=${{ vars.RAILWAY_CLIENT_SERVICE_ID }}
          railway run yarn build:client

  deploy-api:
    name: deploy-api
    runs-on: ubuntu-latest
    needs: [build-api, changes]
    if: needs.changes.outputs.api == 'true' || needs.changes.outputs.shared == 'true'
    container: ghcr.io/railwayapp/cli:latest
    environment: production
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy API
        run: railway up --service=${{ vars.RAILWAY_API_SERVICE_ID }}

  deploy-client:
    name: deploy-client
    runs-on: ubuntu-latest
    needs: [build-client, changes]
    if: needs.changes.outputs.client == 'true' || needs.changes.outputs.shared == 'true'
    container: ghcr.io/railwayapp/cli:latest
    environment: production
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Client
        run: railway up --service=${{ vars.RAILWAY_CLIENT_SERVICE_ID }}
